apiVersion: v1
kind: Pod
metadata:
  name: mlflow
  labels:
    type: model-storage
spec:
  volumes:
    - name: git-repo
      emptyDir: {}
  initContainers:
    - name: git-clone
      image: alpine/git
      command: ["git", "clone", "--single-branch", "--branch", "develop", "https://github.com/MarceloGarcia92/sentimentAnalisys.git", "/repo"]
      volumeMounts:
      - name: git-repo
        mountPath: /repo
  containers:
  - name: mlflow
    image: mgarcia92/mlflow:v1
    ports:
    - containerPort: 5000
    readinessProbe:
      exec:
        command:
        - cat
        - /mlflow/src
      initialDelaySeconds: 10
      periodSeconds: 5
    volumeMounts:
    - name: git-repo
      mountPath: /mlflow