apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-21T23:52:49Z"
  labels:
    type: orchestation
  name: airflow-server
  namespace: default
  resourceVersion: "40622"
  uid: 4b7d0d6e-a785-4eee-8b73-726864206f30
spec:
  clusterIP: 10.105.61.82
  clusterIPs:
  - 10.105.61.82
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    type: orchestation
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
